<?php $this->layout('default', ['active' => 'a']) ?>

<h1>Your account (<?= $user['email'] ?>)</h1>

<h2>Your characters</h2>

<?php if (count($characters) === 0): ?>
  <p>You have no characters yet! Click <b>Add New</b> to get started.</p>
<?php else: ?>
  <ul class="options">
    <?php foreach ($characters as $c): ?>
      <li>
        <a href="<?= $this->link('Character/edit', $c['uniqid']) ?>"><?= $c['char_name'] ?></a>
      </li>
    <?php endforeach ?>
  </ul>
<?php endif ?>

<p>
  <a class="button" href="<?= $this->link('Character/create') ?>">Add New</a>
</p>

<h2>Account options</h2>

<h3>Change password</h3>

<?= $f->start(['class' => 'account']) ?>

  <?= $f->label('Old password:', 'old') ?>
  <?= $f->password('old', ['required' => true, 'minlength' => 8]) ?>

  <?= $f->label('New password:', 'new') ?>
  <?= $f->password('new', ['required' => true, 'minlength' => 8]) ?>

  <?= $f->submit('Change') ?>

<?= $f->end() ?>

<h3>Delete account and characters</h3>

<p>
  <a class="button delete" href="<?= $this->link('User/delete') ?>">Delete</a>
</p>
