<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HTTP 404</title>
  <link rel="stylesheet" href="/style.css">
</head>
<body>
<h1>
  404 <span style="font-weight:300;color:#777">Not Found</span>
</h1>

<p>I don’t know where you were trying to go, but perhaps you should start over at the <a href="/">home page</a>! 🙀</p>
</body>
</html>
